# Generated by Django 3.2.6 on 2022-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='user_name',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
