# Generated by Django 3.2.6 on 2022-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_alter_fcuser_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='user_email',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='유저 이메일'),
            preserve_default=False,
        ),
    ]
